line-length = 80

[lint]
preview = true
select = ["ALL"]
ignore = [
    "D211",
    "D213",
    "D104",
    "RUF067",
    "ANN202",
    "ANN001",
    "DOC201",
    "S101",
    "PTH120",
    "PTH118",
    "PLW1514",
    "D103",
    "D100",
    "INP001",
    "FURB101",
    "ANN201",
    "T201",
    "D205",
    "RUF002",
    "RUF003",
    "CPY001",
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pylint]
max-args = 6

[format]
quote-style = "single"
